;; This logfile was generated automatically by `xindy'
;; at 05.12.2012  23:27:19
;; Indexstyle: "/tmp/aXwXNmFRCp", Rawindex: "/tmp/dUjbvt596O", Output: "TesisLatex.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´—" -> "L"

makeglossaries messages:

Cannot locate xindy module for language spanish in codepage utf8.
Retrying using default codepage.
Cannot locate xindy module for language spanish.
Retrying with -L general
